### ISSUE TITLE
Joint Rotation Definition 

### ISSUE THREAD

**Issue by yufeizhangmeta** [facebookresearch/UHM#3]
Hi,

Thanks for sharing the great work! I see all the joints are defined in the local coordinate but realigned through local_pose and global_pose. I wonder if there is any visualization of the coordinate system after the alignment?

Thanks

**Comment by mks0601** [comment]
Hi, could you elaborate what you mean by 'after the alignment'? You can consider the local_pose (and also the global_pose, which is computed from the local_pose) are just poses in the template space.

**Comment by yufeizhangmeta** [comment]
Hi,

Thanks for the reply. I think, without the local_pose, all the joints would have the same coordinate system as the root joint but having translation difference. Adding the local_pose can change the local joint frame to align with the finger direction (please correct me if this is wrong). I am wondering if there could be some visualization of the local joint frame to study the change due to the local_pose.

yufei

**Comment by mks0601** [comment]
```
 I think, without the local_pose, all the joints would have the same coordinate system as the root joint but having translation difference. Adding the local_pose can change the local joint frame to align with the finger direction (please correct me if this is wrong).
```
-> Yes, you're right.

```
I am wondering if there could be some visualization of the local joint frame to study the change due to the local_pose. I then can figure out how certain hand pose can change the joint rotation in which direction and in what degrees.
```
-> Sorry I do not have a visualization for this purpose :( Could you try with [demo](https://github.com/facebookresearch/UHM/tree/main/UHM#demo)?

**Comment by yufeizhangmeta** [comment]
Got it, good enough now. Thanks!

Yufei
